spring:
  h2:
   console:
     path: /console
     enabled: true
  datasource:
    url: jdbc:h2:file:./db/books;DATABASE_TO_UPPER=false
    username: mazo
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      data-locations: classpath:sql-data/*.sql