spring:
  h2:
   console:
     path: /console
     enabled: true
  datasource:
    url: jdbc:h2:file:./db/books;DATABASE_TO_UPPER=false
    username: mazo
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
