INSERT INTO publisher (name, address, phone) VALUES ('Istanbul Publishing House', 'Istanbul, Turkey', '0212-111-2222');
INSERT INTO publisher (name, address, phone) VALUES ('Ankara Books', 'Ankara, Turkey', '0312-333-4444');
INSERT INTO publisher (name, address, phone) VALUES ('Izmir Press', 'Izmir, Turkey', '0232-555-6666');
INSERT INTO publisher (name, address, phone) VALUES ('Antalya Literature', 'Antalya, Turkey', '0242-777-8888');
INSERT INTO publisher (name, address, phone) VALUES ('Bursa Editions', 'Bursa, Turkey', '0224-999-0000');
INSERT INTO publisher (name, address, phone) VALUES ('Adana Writers', 'Adana, Turkey', '0322-101-2020');
INSERT INTO publisher (name, address, phone) VALUES ('Konya Classics', 'Konya, Turkey', '0332-303-4040');
INSERT INTO publisher (name, address, phone) VALUES ('Trabzon Tales', 'Trabzon, Turkey', '0462-505-6060');
INSERT INTO publisher (name, address, phone) VALUES ('Eskişehir Storytellers', 'Eskişehir, Turkey', '0222-707-8080');
INSERT INTO publisher (name, address, phone) VALUES ('Gaziantep Books', 'Gaziantep, Turkey', '0342-909-0101');
INSERT INTO publisher (name, address, phone) VALUES ('Kayseri House', 'Kayseri, Turkey', '0352-121-3141');
INSERT INTO publisher (name, address, phone) VALUES ('Mersin Media', 'Mersin, Turkey', '0324-151-6171');
INSERT INTO publisher (name, address, phone) VALUES ('Samsun Press', 'Samsun, Turkey', '0362-212-2232');
INSERT INTO publisher (name, address, phone) VALUES ('Denizli Publications', 'Denizli, Turkey', '0252-242-5262');
INSERT INTO publisher (name, address, phone) VALUES ('Sivas Writers', 'Sivas, Turkey', '0342-272-7282');
INSERT INTO publisher (name, address, phone) VALUES ('Malatya Memoirs', 'Malatya, Turkey', '0422-292-9303');
INSERT INTO publisher (name, address, phone) VALUES ('Van Verses', 'Van, Turkey', '0432-313-1415');
INSERT INTO publisher (name, address, phone) VALUES ('Diyarbakır Diaries', 'Diyarbakır, Turkey', '0412-323-3343');
INSERT INTO publisher (name, address, phone) VALUES ('Rize Reads', 'Rize, Turkey', '0464-343-5454');
INSERT INTO publisher (name, address, phone) VALUES ('Sakarya Stories', 'Sakarya, Turkey', '0264-353-6565');

INSERT INTO author (first_name, last_name) VALUES ('Ahmet', 'Yılmaz');
INSERT INTO author (first_name, last_name) VALUES ('Mehmet', 'Demir');
INSERT INTO author (first_name, last_name) VALUES ('Ayşe', 'Kara');
INSERT INTO author (first_name, last_name) VALUES ('Fatma', 'Çelik');
INSERT INTO author (first_name, last_name) VALUES ('Emre', 'Arslan');
INSERT INTO author (first_name, last_name) VALUES ('Selin', 'Aydın');
INSERT INTO author (first_name, last_name) VALUES ('Burak', 'Öztürk');
INSERT INTO author (first_name, last_name) VALUES ('Zeynep', 'Şahin');
INSERT INTO author (first_name, last_name) VALUES ('Can', 'Kılıç');
INSERT INTO author (first_name, last_name) VALUES ('Ece', 'Güneş');
INSERT INTO author (first_name, last_name) VALUES ('Mert', 'Kaya');
INSERT INTO author (first_name, last_name) VALUES ('Elif', 'Özdemir');
INSERT INTO author (first_name, last_name) VALUES ('Ozan', 'Arslan');
INSERT INTO author (first_name, last_name) VALUES ('Sena', 'Yıldırım');
INSERT INTO author (first_name, last_name) VALUES ('Cem', 'Aksoy');
INSERT INTO author (first_name, last_name) VALUES ('Derya', 'Uysal');
INSERT INTO author (first_name, last_name) VALUES ('Burcu', 'Polat');
INSERT INTO author (first_name, last_name) VALUES ('Kerem', 'Gök');
INSERT INTO author (first_name, last_name) VALUES ('Pelin', 'Acar');
INSERT INTO author (first_name, last_name) VALUES ('Oya', 'Özer');

INSERT INTO book (title, price, publisher_id) VALUES ('Tutunamayanlar', 45.50, 1);
INSERT INTO book (title, price, publisher_id) VALUES ('Saatleri Ayarlama Enstitüsü', 39.99, 2);
INSERT INTO book (title, price, publisher_id) VALUES ('Kürk Mantolu Madonna', 55.75, 3);
INSERT INTO book (title, price, publisher_id) VALUES ('İnce Mehmed', 40.00, 1);
INSERT INTO book (title, price, publisher_id) VALUES ('Huzur', 42.25, 4);
INSERT INTO book (title, price, publisher_id) VALUES ('Anayurt Oteli', 38.50, 2);
INSERT INTO book (title, price, publisher_id) VALUES ('Yalnızız', 47.00, 5);
INSERT INTO book (title, price, publisher_id) VALUES ('Sinekli Bakkal', 36.80, 3);
INSERT INTO book (title, price, publisher_id) VALUES ('Fatih Harbiye', 44.90, 6);
INSERT INTO book (title, price, publisher_id) VALUES ('Bir Düğün Gecesi', 41.00, 4);
INSERT INTO book (title, price, publisher_id) VALUES ('Çalıkuşu', 50.30, 7);
INSERT INTO book (title, price, publisher_id) VALUES ('Aşk-ı Memnu', 53.20, 8);
INSERT INTO book (title, price, publisher_id) VALUES ('Yaban', 37.40, 2);
INSERT INTO book (title, price, publisher_id) VALUES ('Eylül', 39.60, 9);
INSERT INTO book (title, price, publisher_id) VALUES ('Acımak', 43.80, 10);
INSERT INTO book (title, price, publisher_id) VALUES ('Dokuzuncu Hariciye Koğuşu', 48.00, 11);
INSERT INTO book (title, price, publisher_id) VALUES ('İstanbul Hatırası', 52.50, 12);
INSERT INTO book (title, price, publisher_id) VALUES ('Beyaz Kale', 47.90, 13);
INSERT INTO book (title, price, publisher_id) VALUES ('Karanlıkta Yolculuk', 46.70, 1);
INSERT INTO book (title, price, publisher_id) VALUES ('Kayıp Aranıyor', 42.10, 2);

INSERT INTO book_authors (book_id, authors_id) VALUES (1, 1);
INSERT INTO book_authors (book_id, authors_id) VALUES (1, 2);
INSERT INTO book_authors (book_id, authors_id) VALUES (2, 3);
INSERT INTO book_authors (book_id, authors_id) VALUES (2, 4);
INSERT INTO book_authors (book_id, authors_id) VALUES (3, 5);
INSERT INTO book_authors (book_id, authors_id) VALUES (3, 3);
INSERT INTO book_authors (book_id, authors_id) VALUES (4, 6);
INSERT INTO book_authors (book_id, authors_id) VALUES (4, 7);
INSERT INTO book_authors (book_id, authors_id) VALUES (5, 8);
INSERT INTO book_authors (book_id, authors_id) VALUES (6, 9);
INSERT INTO book_authors (book_id, authors_id) VALUES (6, 10);
INSERT INTO book_authors (book_id, authors_id) VALUES (7, 11);
INSERT INTO book_authors (book_id, authors_id) VALUES (7, 12);
INSERT INTO book_authors (book_id, authors_id) VALUES (7, 2);
INSERT INTO book_authors (book_id, authors_id) VALUES (8, 13);
INSERT INTO book_authors (book_id, authors_id) VALUES (9, 14);
INSERT INTO book_authors (book_id, authors_id) VALUES (9, 15);
INSERT INTO book_authors (book_id, authors_id) VALUES (10, 16);
INSERT INTO book_authors (book_id, authors_id) VALUES (11, 17);
INSERT INTO book_authors (book_id, authors_id) VALUES (11, 18);
INSERT INTO book_authors (book_id, authors_id) VALUES (12, 19);
INSERT INTO book_authors (book_id, authors_id) VALUES (12, 20);
INSERT INTO book_authors (book_id, authors_id) VALUES (13, 1);
INSERT INTO book_authors (book_id, authors_id) VALUES (14, 2);
INSERT INTO book_authors (book_id, authors_id) VALUES (14, 3);
INSERT INTO book_authors (book_id, authors_id) VALUES (15, 4);
INSERT INTO book_authors (book_id, authors_id) VALUES (15, 5);
INSERT INTO book_authors (book_id, authors_id) VALUES (16, 6);
INSERT INTO book_authors (book_id, authors_id) VALUES (17, 7);
INSERT INTO book_authors (book_id, authors_id) VALUES (17, 8);
INSERT INTO book_authors (book_id, authors_id) VALUES (18, 9);
INSERT INTO book_authors (book_id, authors_id) VALUES (18, 10);
INSERT INTO book_authors (book_id, authors_id) VALUES (19, 11);
INSERT INTO book_authors (book_id, authors_id) VALUES (20, 12);
INSERT INTO book_authors (book_id, authors_id) VALUES (20, 13);
